#
# libzmq readthedocs.io integration
#
# This configuration file is processed by readthedocs.io to rebuild the
# libzmq documentation using Asciidoctor, see
#   https://docs.readthedocs.io/en/stable/build-customization.html#asciidoc

version: "2"

formats:
  - htmlzip

build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "20"
  # NOTE: as of Nov 2023, build.apt_packages is NOT considered when using build.commands
  #apt_packages:
  #  - automake
  #  - autoconf
  #  - cmake
  #  - libtool
  commands:
    - npm install -g asciidoctor
    - asciidoctor --backend html --destination-dir $READTHEDOCS_OUTPUT/html --attribute zmq_version='4.1.x' doc/*.txt
    # we use as landing page the "zmq.html":
    - cp $READTHEDOCS_OUTPUT/html/zmq.html $READTHEDOCS_OUTPUT/html/index.html
    # htmlzip docs are just like HTML:
    # NOTE: for usability we make sure zip will create a zipfile containing just a flat list of HTML files; to achieve that
    #       it's important to avoid storing absolute paths when invoking "zip", thus we use -j
    - mkdir -p $READTHEDOCS_OUTPUT/htmlzip/
    - cd $READTHEDOCS_OUTPUT/html && zip -j ../htmlzip/f18m-libzmq.zip *.html
